services:
  node:
    build:
      context: .
      dockerfile: dockerfile.dev
    user: node
    working_dir: /home/node/app
    volumes:
      - ${SITE_DIR}/:/home/node/app
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    command: npx nodemon template.js
